[package]
name = "ade-filesystem"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description = "ADE: OFS/FFS mount, dostypes, directory traversal, RDB partitions"

[dependencies]
ade-block = { workspace = true }
ade-endian = { workspace = true }
[dev-dependencies]
ade-block = { workspace = true }
ade-endian = { workspace = true }
ade-fixtures = { workspace = true }

[lints]
workspace = true
