[package]
name = "ade-catalogue"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description = "ADE: content hashing, dataset matching, reporting, export"

[dependencies]
ade-object = { workspace = true }
ade-block = { workspace = true }
[lints]
workspace = true
